### ISSUE TITLE
Rodrigo, Edit Bio! Add Skills

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#103]
Add your skills/capacities. You just need 3 sentences that highlight this. We don't need any more history/current roles.

Here's the bio doc:
https://docs.google.com/a/berkeley.edu/document/d/1_9_pxxMkQKzB67iftP1ax_I53Bisw_1jz9Buzh2Ve-I/edit#

**Comment by gar-bear** [comment]
@mitar , should I leave Rodrigo on?

**Comment by mitar** [comment]
Let's close for now. If she becomes more active again, we can redo this again then. Until then, we have a great fan and occasional contributor. :-)

**Comment by mitar** [comment]
Let's close for now. If she becomes more active again, we can redo this again then. Until then, we have a great fan and occasional contributor. :-)
