### ISSUE TITLE
Kathleen! Edit Bio! Add Skills!

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#115]
Add your skills/capacities. You can just email me, or post here, 3 sentences that highlight this. We don't need any more history/current roles.

**Comment by gar-bear** [comment]
Hello,

Is this person still with us or shall I close this ticket?

**Comment by mitar** [comment]
Let's close for now. If she becomes more active again, we can redo this again then. Until then, we have a great fan and occasional contributor. :-)
