### ISSUE TITLE
Write a doc with bullet points on how we're different from Mendeley

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#144]
This is important, especially for those new to outreach, and devs representing us in professional settings.

**Comment by gar-bear** [comment]
We can clean this up and make it beautiful, but I believe this is the idea:
https://docs.google.com/document/d/16GTHWfPMzUuF7_g0CeomuISUrgu5UaE3PY3ujqNLc3o/edit

Let me know if I shouldn't close this, okay?

**Comment by gar-bear** [comment]
Okay, I took what we have so far and put it into a GoogleDoc called, "Us vs. Them" in Promo Material.
I will close for now, but if y'all want to reopen it and make it more beautiful, I totally understand.
