### ISSUE TITLE
Blog Post about new logo

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#159]
Title explains this. Just let them know we've updated our logo, a precursor to the improvements to our site coming in q1 of next year.

**Comment by gar-bear** [comment]
Will someone give me access to Tumblr in order to publish it?
Thank you!

My report: I had lots of fun writing this. It was going to be twice as long, but after much deliberation with Mitar, I decided against my original plan. I hope you all enjoy reading it as much as I did.

https://docs.google.com/a/berkeley.edu/document/d/1qfGnXqDeBnCrEwWyPRcOBU5WBx4phXIPOWDjZw1ryJY/edit

**Comment by mitar** [comment]
Why you closed it? Is it published?

**Comment by gar-bear** [comment]
It is not published yet.

**Comment by mitar** [comment]
Then the task is not yet finished and you should not close the ticket.

**Comment by gar-bear** [comment]
Sounds good.

**Comment by gar-bear** [comment]
I got a Tumblr account.
Please review the GoogleDoc, so we can publish this as soon as possible, okay?

https://docs.google.com/a/berkeley.edu/document/d/1qfGnXqDeBnCrEwWyPRcOBU5WBx4phXIPOWDjZw1ryJY/edit

@raaswol @mitar @ciaobrian

**Comment by mitar** [comment]
I checked it. See comments there. I think it is nice, but I am again unsure if we want such level of conversation or something more serious. On one hand I think, why not. Let just be like that. Others do not gave Gary and are so boring to read. :-) We should have fun doing this. So, @gar-bear, check the comments, address them, and then publish. :-)

**Comment by mitar** [comment]
One useful thing would also be to make on the blog post at the top old and new logo images. So that people can see what we are talking about. We can make first just logo, then small introductory line telling about the logo change, and the "break", and then the rest. "break" on Tumblr is a way to make (second) part of the blog post appear only when blog post is read on its own page, and on the index/first page is not displayed. You get "read more" link. In this way we can have both short and long versions.

**Comment by mitar** [comment]
See [how to add a break here](http://unwrapping.tumblr.com/post/109650701082/read-more-link-tumblr-posts).

**Comment by gar-bear** [comment]
Last concerns have been resolved, in my opinion.
When the GoogleDoc is settled, I will post the blog on Tumblr, with your breaks included, Mitar

**Comment by mitar** [comment]
I like it.

**Comment by gar-bear** [comment]
Any last words anyone before I publish it on Tumblr?
I'll set it to post at six o' clock tomorrow. =]

@Klarster , would you mind taking a look?

**Comment by mitar** [comment]
Cool.

**Comment by Klarster** [comment]
Thumbs up :D Btw, is it going to be posted on LinkedIn automatically as well?

**Comment by mitar** [comment]
I do not think things are going automatically anywhere. Twitter, Linkedin, Facebook, AngelList.

**Comment by Klarster** [comment]
I was referring to #82. Has anyone looked into that?

**Comment by mitar** [comment]
I don't think so.

**Comment by Klarster** [comment]
@gar-bear, could you try to connect these accounts: Tumblr, Twitter, LinkedIn, Facebook?

**Comment by gar-bear** [comment]
Yes I can, but I don't have access to the LinkedIn or Twitter.
If someone gives me access, I'll try to sync them all up. =]

On Wed, Apr 8, 2015 at 10:18 AM, Klara Pelcl <notifications@github.com>
wrote:

> @gar-bear <https://github.com/gar-bear>, could you try to connect these
> accounts: Tumblr, Twitter, LinkedIn, Facebook?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peerlibrary/outreach/issues/159#issuecomment-90979055>
> .
>



-- 
*Gary Richmond*
Zero Waste Research Center Program Associate
The Green Initiative Fund

PeerLibrary - Outreach and Academic Support

*LEAD Center | **ASUC Student Union | University of California, Berkeley*
102 Hearst Gym MC 4500 | Berkeley CA 94720-4500
*e.* gar-bear@berkeley.edu | *tgif.berkeley.edu* <http://tgif.berkeley.edu/>
*Follow us*: Facebook <https://www.facebook.com/thegreeninitiativefund> |
Twitter <https://twitter.com/TGIF_UCB> | Newsletter
<http://us3.campaign-archive1.com/home/?u=8c4a45c0abc1f3bf1b36e8919&id=f5b8cfc4ae>

**Comment by Klarster** [comment]
So, I believe @ciaobrian has access to both. Could you solve this together?

**Comment by ciaobrian** [comment]
Hi I have access to linkedin but not twitter :) do you have a linked in account gary?

**Comment by Klarster** [comment]
@gar-bear , I believe @mitar  can give you access to Twitter (I don't have access to Twitter either), and @ciaobrian  could invite you to LinkedIn as soon as you create a profile there.
