### ISSUE TITLE
Submit A Proposal for UCB's Department of Equity & Inclusion Innovative Grants Program

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#167]
Dear UC Berkeley Students, Faculty, and Staff:

The Division of Equity & Inclusion is pleased to announce a Request for
Proposals ( http://diversity.berkeley.edu/innovationgrants ) for
innovative projects that will make our campus a more inclusive place to
study and work. This opportunity comes as part of the Chancellor’s
Campus Climate Initiative, announced in March 2014 as an initial
response to the results of the 2013 UC Berkeley Campus Climate Survey (
http://diversity.berkeley.edu/campus-climate ). The survey found that 1
in 4 people on campus experienced some form of exclusion, intimidation,
bullying, or isolation during the previous year. These findings are a
compelling call to action for innovative ways to make UC Berkeley a more
equitable and inclusive community. The 2014 – 2015 Innovation Grants for
Equity, Inclusion, and Diversity invite your best collaborative ideas
for new and creative projects to accomplish this goal for all students,
faculty, and staff. The grants provide modest resources towards that
end, with a preference for projects with the greatest potential for
sustainable success.

The 2014 - 2015 Innovation Grants program is open to all UC Berkeley
students, staff, and faculty with a current CalNet ID. Click here (
http://diversity.berkeley.edu/innovationgrants ) for the full Request
for Proposals. Proposals are due Monday, February 16, 2015 by 5pm in
electronic format to equity_inclusion@berkeley.edu (
mailto:equity_inclusion@berkeley.edu ).

For the past four years, Equity & Inclusion has sponsored the Innovation
Grants program, an initiative that provides seed funding for projects
designed to advance groundbreaking programs of inclusion at UC Berkeley.
Past Innovation Grants awards have resulted in enhanced accessible
fitness programs, including the first competitive college athletic team
for blind students (
http://newscenter.berkeley.edu/2014/09/22/new-athletic-team-breaks-barriers-for-the-disabled/
); an expansion of the Cal Veterans program (
http://newscenter.berkeley.edu/2014/11/07/cal-veterans-services-to-expand/
); a new pathway to graduate school for undocumented undergraduate
students; and the first faculty mentorship program for students with
Autism Spectrum Disorder (ASD), among many others. All of these projects
demonstrate the power of harnessing innovative ideas to transform
Berkeley into a community where opportunity and inclusion are both
valued and practiced.

The Office of the Vice Chancellor for Equity & Inclusion can provide
assistance to individuals and groups during the proposal process. Call
(510) 642-8828 or email egillis@berkeley.edu (
mailto:egillis@berkeley.edu ) for questions about the proposal process,
or attend an information session:

-Wednesday, December 10, 2014, (12noon – 1pm), Room 331 Sproul Hall

-Thursday, January 15, 2015, (10:30am – 11:30am), Room 331 Sproul Hall

I look forward to receiving innovative and sustainable proposals from
across the campus to further excellence, equity, and inclusion at UC
Berkeley.

With best regards,

Gibor Basri
Vice Chancellor for Equity & Inclusion
http://diversity.berkeley.edu

*This project is also supported by the Evelyn and Walter Haas, Jr. Fund
and is part of the UC Berkeley Initiative for Equity, Inclusion, and
Diversity (
http://diversity.berkeley.edu/uc-berkeley-initiative-equity-inclusion-and-diversity
).

**Comment by Klarster** [comment]
Sooo, I messed this one up. Overdue now :/ Proposals are due Monday, February 16, 2015 by 5pm. Closing this ticket now.
