### ISSUE TITLE
Create User Guide

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#180]
self-explanatory. She's already working on this.

**Comment by Klarster** [comment]
Aaand done :). Check out if there is something I missed. I plan on adding some screenshots soon, or if we could get some people to shoot a video - that would be awesome, too :)

**Comment by mitar** [comment]
Link?

We also have a screencast already: https://vimeo.com/109787685 This is not enough of a video?

**Comment by Klarster** [comment]
https://docs.google.com/document/d/1xISh55U_xy7Jq_CHcxTEoexZ49nh-_4UCRzqLNT-rks/edit . And yes, this video is enough - I actually haven't seen it yet! looks great! :D
