### ISSUE TITLE
Gar's Passport Preponderance and Potential Problem

### ISSUE THREAD

**Issue by gar-bear** [peerlibrary/outreach#181]
Hey, those who may care!

My report on getting the passport situation understood sounds like this:

1. After Finals, I looked into it and discovered that I indeed needed to renew my license BEFORE getting a passport.
2. December 23rd I walked to the South Side of campus and took the 51B South to Claremont in Oakland. From there, I walked seven blocks to the City of Oakland DMV and waited >3 hours while they were hoping their system would start functioning again - it did not that day.
3. I went back Christmas Eve, December 24th, got my license renewed (they send the ACTUAL ID through the mail), which means that I received a piece of paper that claims to be my "Interim Driver License" that day.
4. In Napa, I am with family of whom I questioned about the possibility of me already having a Passport perhaps, but the resounding answer was no.
5. I began calling the Napa post office that handles passports, they refused to answer their phone (~8 phone calls).
6. Doing online research, I discovered that the Passport people may take issue with my Birth Certificate (I do not have a certified copy) AND my driver license (I have a valid "Interim" one and an expired one with a photograph of me).
7. I went down to the Post Office, since the phone was not accomplishing anything and I discovered that they are no longer taking appointments.
8. I called the 877 number for passports and they directed me to an agency that may be able to see me NEXT WEEK.
9. What worries me is that if the process takes even just a few days to get the passport back to me I cannot go. I don't want to gamble somebody not going to FORCE, so I am 100% willing to help prepare the materials for the presentation, but I'm worried that if all of this is riding on me getting on a plane, we are setting ourselves up for disappointment. Maybe if I get more sleep this will not seem like such a big deal to me, but I'm really fretting about it right now.

Ten-four,
Gary

**Comment by ciaobrian** [comment]
@mitar  @raaswol  ?

**Comment by mitar** [comment]
Yes, working on this, it seems @raaswol will go instead.

**Comment by raaswol** [comment]
We are waiting to hear back from the Force people on whether I can replace him or not. Their last email said they will respond Jan 5th when they return to the office. 

Since Gary filled out a very personal application for the scholarship and the answer wasn't an automatic yes, I'm going to respond with my letter of motivation and some details about why the change.

Correspondence with them has been professional; as well as down to earth. So my response and those so far, as in all such cases, include: 
thanking them for responding while on their holiday, 
thanking them for the the opportunity,
 in this case apologize for the mix up, 
and because of their being out of their message delaying a response, I'll add some phrase that let's them know I'm not expecting them to respond right now.

**Comment by raaswol** [comment]
Hi mitar! lol I was just responding to this :-)

**Comment by raaswol** [comment]
Thank you for staying on top of this, and helping in every way you can. You rock gar-bear!

**Comment by gar-bear** [comment]
Thank you! I tried to see it through. =]

On Mon, Jan 5, 2015 at 5:42 PM, raaswol <notifications@github.com> wrote:

> Thank you for staying on top of this, and helping in every way you can.
> You rock gar-bear!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peerlibrary/outreach/issues/181#issuecomment-68813967>
> .
>



-- 
*Gary Richmond*
Zero Waste Research Center Program Associate
The Green Initiative Fund

PeerLibrary - Outreach and Academic Support

*LEAD Center | **ASUC Student Union | University of California, Berkeley*
102 Hearst Gym MC 4500 | Berkeley CA 94720-4500
*e.* gar-bear@berkeley.edu | *tgif.berkeley.edu* <http://tgif.berkeley.edu/>
*Follow us*: Facebook <https://www.facebook.com/thegreeninitiativefund> |
Twitter <https://twitter.com/TGIF_UCB> | Newsletter
<http://us3.campaign-archive1.com/home/?u=8c4a45c0abc1f3bf1b36e8919&id=f5b8cfc4ae>
