### ISSUE TITLE
Force2015

### ISSUE THREAD

**Issue by raaswol** [peerlibrary/outreach#182]
* Run through the presentation I'll give on my own and make sure everything is smooth (in this case a poster and demo station) .

* Post an agenda to github of 
-what sessions I find relevant to peerlibrary,
-times I'll be available (not presenting) and what's on at that time so anyone back home can request I go to that session if they find it relevant.

**Comment by raaswol** [comment]
In this case, since I'd be replacing our original delegate:
- Add Gary's thoughtful writing to the basic bullet points (for me to interject at the demo station)
-Make a poster from Jared's vision session abstract, since he applied for a different format.
_I need to check if I can bring it on the plane. I'll probably get bendable board, roll it up to get there, and get harder board to tape it to when I'm there._
-Find the overlap between the two and visualize manning two stations

**Comment by mitar** [comment]
No, poster should be a presentation of PeerLibrary. The vision format was for session, if we would get it. Did we?

**Comment by mitar** [comment]
So our focus should be presenting PeerLibrary and demoing it. Session was extra, if we would get it.

**Comment by raaswol** [comment]
I'll send you the email Gary got. Demo presents Peerlibrary, what Gary's application asked to do. It's different from a poster session.
Additionally Gary was signed up to do a poster, and Jared's vision session is the application they accepted for that. You can tell by the title.

**Comment by mitar** [comment]
I don't get anything anymore. :-) But I see you are on the top of the things, so just carry on. :-)

**Comment by raaswol** [comment]
I'll ask gary to forward us the emails :-)

**Comment by raaswol** [comment]
Here is the agenda I plan on following. 
Only the first pre-conference day is tentative/time dependent, I'll be attending everything else.
When I know the breakout groups, I'll post them :-)

https://www.force11.org/meetings/force2015/agenda

Jan 11th
13-16h  Future Commons
13-18h Contribution/Attribution Context of Scholar OR Common APIs FAIR data repos
15-18h ContentMine Wrkshp


Jan 12 (Attending All)
Start Time	End Time	Session	Room/Location
07:00	18:00	Registration	Mathematical Institute
08:00	09:00	Light breakfast: Coffee, tea and pastries	 
ALL DAY	 	     HACK Space available (live streaming of main session into Hack Room)	e-Research                  
                             Center - Room 278
09:00	09:15	Opening Session: Introductions and Updates	 
09:15	09:25	Philosophical Transactions of the Royal Society (1665)	 
09:25	10:30	Keynote: Communication with a Crowd: Lessons from Citizen Science    Chris  
                                  Lintott, University of Oxford	 
10:30	11:00	Coffee Break	 
11:00	11:30	Updates from 1K and FORCE11 Activities	 
11:30	12:45	Session:  Valuing the Diversity of Scholarly Impact in a Networked World	 
12:45	14:15	Lunch and Tour to visit Philosophical Transactions of the Royal Society	 
14:15	15:15	Keynote: Managing Data: The Long View   Amy Friedlander, National Science 
                                Foundation	 
15:15	15:45	Ice Cream Break - Sponsored by Elsevier and Mendeley
15:45	17:00	Panel: True or False? Transparency, Validation, and Reproducibility of Research in  
                                Scholarly Communication	 
17:00	17:05	Demo Previews	 
17:05	17:30	Session:  Summary of Day	 
18:30	21:30	Data, Demos, and Drinks posters and demos reception

Jan 13 (Attending All)
Start Time	End Time	Session	Room/Location
07:00	18:00	Registration	 
08:00	09:00	Light breakfast: Coffee, tea and pastries	 
All Day	 	        HACK Space Available (live stream of main session into Hack Room)	 
09:00	10:00	Keynote: Libraries of Scale: Global Partnerships and Scholarly Access   Sarah 
                                Thomas, Harvard University	 
10:00	10:15	Coffee Break	 
10:15	11:30	Vision Session:  5-minute Flash Talks - Great Ideas!	 
11:30	13:00	Session:  Credit Where Credit is Due	 
13:00	14:15	Grab a Box Lunch and Join a Birds of Feather Group	 
14:15	15:30	Panel:  Funding Panel: Innovative Funding Models	 
15:30	16:15	Session:  Outcomes from Breakout Sessions and Workshops	 
16:15	16:45	Traditional English Tea Break	 
16:45 	18:00	Session:  Geek Out - Research on the Web	 
18:00	18:30	Closing Session:  Where Have We Been and Where are We Going as a 
                                Community?  Phil Bourne, NIH

**Comment by raaswol** [comment]
Things to look into when visitng a conference:
Transportation - times, prices, exact locations.
Accommodations - location, price, check in/out times, wifi.
Food (you can bring some :-)) - location, price ranges.
Agenda at the conference - check with your team members for their interest!
User Reviews for all the above and attractions if you'll be touring.

Internationally:
Phone service there, check w/ your provider or for a temporary option.
Electrical outlet conversion, when abroad.

For those using this page as a reference, if you're visiting England, here are some resources:
Trains:
http://www.southwesttrains.co.uk/plan-your-journey.aspx
http://tickets.firstgreatwestern.co.uk/gw/en/JourneyPlanning/MixingDeck
& the the underground in London

& railcard makes it cheaper - http://www.railcard.co.uk/

One gets from the city to LHR at Paddington station. 
Paddington is a waypoint for pretty much all transportation.

Accom.:
http://www.yha.org.uk/

**Comment by raaswol** [comment]
Rachel is going! Confirmed today. :)

**Comment by raaswol** [comment]
@mitar @spencerhitch @opalkale I can't find the videos of 1)Screencast 2)Promo w/ or w/out IA

**Comment by raaswol** [comment]
Once we have funding we can order the other swag. Right now, a presenter needs:
 * [x] Screencast video
 * [x] Slides
 * [ ] Bullet points / Talking Points
 * [ ] FAQs 
- [ ] Print those FAQs if you're stations, such as poster or demo
 * [x] Business cards

If w/ a long presentation, which Force is not:
 * [ ] Speaking/Long presentation

**Comment by mitar** [comment]
* Old promo: https://vimeo.com/93085636
* Screencast: https://vimeo.com/109787685

**Comment by gar-bear** [comment]
Over as far as I'm aware. =]
