### ISSUE TITLE
Application to POC21

### ISSUE THREAD

**Issue by kocakafa** [peerlibrary/outreach#186]
anyone interested?
http://poc21.cc/

**Comment by Klarster** [comment]
Sounds great, but I am not sure if this is really for us.
It would take quite a lot of money to get a couple of our developers to EU, and we are already in need of funding ourselves. That being said, it still looks like a nice opportunity to speed up our development as well as outreach at the same time. @mitar ?

**Comment by kocakafa** [comment]
on [this page](https://docs.google.com/forms/d/1nur05JKoASOdCMEQZIVpKKZIEZ5uLbpv0RejS8rhej8/viewform) it says: 
( --- We Got You Covered --- ) 
Our aim is to be able to fully fund your stay with us during the five weeks, including food, tools, materials, party, travel and accommodation at the castle.

**Comment by kocakafa** [comment]
I'd like to apply and be there for the event. I am willing to cover all the necessary expenses. It seems to me a big deal in the sense of outreach.
What do you say?

**Comment by mitar** [comment]
This looks really great. I would be glad if you could go there and represent PeerLibrary. I will be also in Europe at that time, at http://battlemesh.org/. Do you need any help from our side for this?

**Comment by kocakafa** [comment]
Ofcourse, i'd be happy if we could double check my actions at the event. Presentation, invitations to new coders and so on. I will inform you all on this.

**Comment by mitar** [comment]
So, what is the progress on this?

**Comment by kocakafa** [comment]
We are waiting for the response. I made a simple application based on Knight Foundation application on gDrive. The organizers expressed they are prioritizing open source hardware projects.

**Comment by kocakafa** [comment]
The response address is hello@peerlibrary.org, fyi.

**Comment by kocakafa** [comment]
:(

> Hello,
> thank you very much for your time and effort you put into applying for the POC21 innovation camp.
> 
> We were overwhelmed by +170 project applications and really were spoilt for choice because only the top12 will make it into the camp. After screening each and every single one in detail, I have to tell you that unfortunately your project was not selected to join POC21 this summer.
> 
> There´s s variety of reasons why we chose a different project than yours. For example, sometimes we couldn´t see the connection to our main topic of sustainable living clearly enough or the project was still more on the idea or concept stage or we felt like your approach is simply thought to big to really make a dent in 5 weeks. But most of the time we had to take tough decisions to assemble the perfect camp team covering all our areas AND uniting all needed skills at the same time. So sometimes we even had to turn down really great projects. Unfortunately our space and ressources are limited after all and we try to find the best setup for everybody involved. If you´re interested in the specific reasons why we did not shortlist your project in the end, please feel free to drop me a line at dominik@openstate.cc
> 
> After fundraising for more than three years to finally make POC21 a reality this summer, we know all about disappointments. We hope you´ll stay interested in POC21 nevertheless and follow our development, there´s a lot upcoming:
> 
> There will be a call for  supporters and mentors very soon, to join us at the castle and work with the projects.
> We would be very grateful if you could spread and support our crowdfunding campaign in June.
> Above all it would be great to keep you and your team as part of the wider POC21 community, because after the camp the real work only starts: Spreading open-source, sustainable products to mainstream users.
> 
> Please keep in touch and thank you very much for applying again!
> 
> All the best from Berlin and Paris,
> Dominik, Daniel, Simon, Justyna and Ben.

**Comment by mitar** [comment]
:-(
