### ISSUE TITLE
OpenAIRE Open Peer Review Tender Call

### ISSUE THREAD

**Issue by kocakafa** [peerlibrary/outreach#187]
Peer review is evolving – help shape its future!
 
OpenAIRE invites tenders for two prototypes (technologies or workflows) in the area of open peer review. Tenders should build upon or align with the OpenAIRE infrastructure, including zenodo.org.
 
OpenAIRE supports OA infrastructure in Europe and beyond to help realize Open Science for the benefit of society, innovation and industry. OpenAIRE2020, the current project phase, is investigating new modes of scholarly communication, including new approaches to peer review. This invitation to tender forms part of this effort.
 
The work aims to:
-          Encourage technological experimentation in the area of open peer review.

-          Investigate ways in which open peer review technologies might integrate with OpenAIRE’s infrastructure, including the repository Zenodo.org as well as other content aggregated, inferred, and interlinked by OpenAIRE.

-          Provide case studies for evaluation in OpenAIRE’s wider investigation of open peer review.

 
2 x funding up to a maximum of EUR 25,000 (excluding VAT, including expenses) is available for these prototypes.
 
The deadline for receipt of tenders is 17:00 CEST Friday 5th June 2015.
 
Innovation, imagination and experimentation are highly encouraged!
 
How to Apply / Documentation
For more details on the call specifications and application procedure, please see the tender call document (https://www.openaire.eu/open-peer-review-tender1/view-document).
 
If you have any queries, please contact Tony Ross-Hellauer (email: ross-hellauer@sub.uni-goettingen.de).
 
With many thanks,
 
Tony

**Comment by gar-bear** [comment]
Hey all,

Okay after reading through the .pdf I believe we can apply to this, but
we'll have to be dazzling to even compete.
My thoughts:
- Mitar will need to be the model of our proposal as he is the
  Professional among us.
- The only, "Specific Objective," that we really have on our side is,
  "User annotations and comments."
- This project takes place from August to early 2016, so this is a LONG
  term project.

They're only going to give two of these awards out, so I want to know from
y'all if it will be worth the time.

On Mon, May 11, 2015 at 5:10 AM, Cemre Kutluay notifications@github.com
wrote:

> Peer review is evolving – help shape its future!
> 
> OpenAIRE invites tenders for two prototypes (technologies or workflows) in
> the area of open peer review. Tenders should build upon or align with the
> OpenAIRE infrastructure, including zenodo.org.
> 
> OpenAIRE supports OA infrastructure in Europe and beyond to help realize
> Open Science for the benefit of society, innovation and industry.
> OpenAIRE2020, the current project phase, is investigating new modes of
> scholarly communication, including new approaches to peer review. This
> invitation to tender forms part of this effort.
> 
> The work aims to:
> 
>    -
> 
> ```
>     Encourage technological experimentation in the area of open peer review.
> ```
> 
>    -
> 
> ```
>     Investigate ways in which open peer review technologies might integrate with OpenAIRE’s infrastructure, including the repository Zenodo.org as well as other content aggregated, inferred, and interlinked by OpenAIRE.
> ```
> 
>    -
> 
> ```
>     Provide case studies for evaluation in OpenAIRE’s wider investigation of open peer review.
> ```
> 
> 2 x funding up to a maximum of EUR 25,000 (excluding VAT, including
> expenses) is available for these prototypes.
> 
> The deadline for receipt of tenders is 17:00 CEST Friday 5th June 2015.
> 
> Innovation, imagination and experimentation are highly encouraged!
> 
> How to Apply / Documentation
> For more details on the call specifications and application procedure,
> please see the tender call document (
> https://www.openaire.eu/open-peer-review-tender1/view-document).
> 
> If you have any queries, please contact Tony Ross-Hellauer (email:
> ross-hellauer@sub.uni-goettingen.de).
> 
> With many thanks,
> 
> Tony
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/peerlibrary/outreach/issues/187.

## 

_Gary Richmond_
Zero Waste Research Center Program Associate
The Green Initiative Fund

PeerLibrary - Outreach and Academic Support

_LEAD Center | *_ASUC Student Union | University of California, Berkeley*
102 Hearst Gym MC 4500 | Berkeley CA 94720-4500
_e._ gar-bear@berkeley.edu | _tgif.berkeley.edu_ http://tgif.berkeley.edu/
_Follow us_: Facebook https://www.facebook.com/thegreeninitiativefund |
Twitter https://twitter.com/TGIF_UCB | Newsletter
http://us3.campaign-archive1.com/home/?u=8c4a45c0abc1f3bf1b36e8919&id=f5b8cfc4ae

**Comment by gar-bear** [comment]
Also, is anyone here familiar with http://zenodo.org/ ?
Our project must integrate with OpenAIRE technologies!!!!!!

"Investigate ways in which open peer review technologies might integrate with
OpenAIRE’s infrastructure, including the repository Zenodo.org as well as other
content aggregated, inferred, and interlinked by OpenAIRE."

**Comment by Klarster** [comment]
Hi all,

So, I created this: https://docs.google.com/document/d/1cC6YiK6c6NMfTGi51M4vkXqnvbF_VPUAwx44TdjjyII/edit. 
We should go ahead and apply, but we only have time until Friday, so we better hurry :)

**Comment by mitar** [comment]
Applied. Thanks for the help.

**Comment by mitar** [comment]
> We are sorry to say that your bid has not been accepted.

:-(
