### ISSUE TITLE
We should update out logo everywhere

### ISSUE THREAD

**Issue by mitar** [peerlibrary/outreach#40]
We have currently around the black old P logo, which should be updated to new book logo. So on Twitter, GitHub, Gravatar, favicon, everywhere.

**Comment by Klarster** [comment]
Hi,

I updated the logo on Angellist, Facebook and LinkedIn. Could somebody do the same with Tumblr and Twitter?

**Comment by gar-bear** [comment]
Twitter and Tumblr are done now. =]
