### ISSUE TITLE
Short official email announcement/summary of the project

### ISSUE THREAD

**Issue by mitar** [peerlibrary/outreach#94]
I was asked for a "short official email announcement/summary of the project that we send out". We should prepare one ([wiki to put things in is already available](https://github.com/peerlibrary/outreach/wiki/Promotion-Materials)). We should probably make it for various target groups, various variations:
* for librarians
* for teachers
* for researchers
* for university administration
* for general public

**Comment by raaswol** [comment]
generally completed, but not reported on.
